import:
  write: yes
  move: yes
    #plugins: convert chroma embedart fetchart lyrics thumbnails
plugins: convert chroma embedart fetchart thumbnails
convert:
  dest: ~/Music-Converted
  format: opus
  auto: no
  copy_album_art: yes
  never_convert_lossy_files: yes

fetchart:
  auto: yes
  sources: filesystem coverart itunes amazon albumart wikipedia

embedart:
  auto: yes

lyrics:
  auto: yes

thumbnails:
  auto: yes
